/** Common community nicknames -> localized hero name. Keys are normalized (lowercase, alphanumeric). */
export const HERO_ALIASES: Record<string, string> = {
  am: "Anti-Mage",
  bs: "Bloodseeker",
  bh: "Bounty Hunter",
  bm: "Beastmaster",
  cm: "Crystal Maiden",
  ck: "Chaos Knight",
  dk: "Dragon Knight",
  dp: "Death Prophet",
  es: "Earthshaker",
  ember: "Ember Spirit",
  earth: "Earth Spirit",
  void: "Faceless Void",
  fv: "Faceless Void",
  qop: "Queen of Pain",
  lc: "Legion Commander",
  ls: "Lifestealer",
  naix: "Lifestealer",
  np: "Nature's Prophet",
  furion: "Nature's Prophet",
  od: "Outworld Devourer",
  pa: "Phantom Assassin",
  pl: "Phantom Lancer",
  sf: "Shadow Fiend",
  ss: "Shadow Shaman",
  sk: "Sand King",
  sb: "Spirit Breaker",
  ta: "Templar Assassin",
  tb: "Terrorblade",
  storm: "Storm Spirit",
  wr: "Windranger",
  wk: "Wraith King",
  wd: "Witch Doctor",
  veno: "Venomancer",
  ww: "Winter Wyvern",
  ench: "Enchantress",
  aa: "Ancient Apparition",
  ns: "Night Stalker",
  kotl: "Keeper of the Light",
  cent: "Centaur Warrunner",
  timber: "Timbersaw",
  techies: "Techies",
  invo: "Invoker",
  magnus: "Magnus",
  mag: "Magnus",
  doom: "Doom",
  necro: "Necrophos",
  sniper: "Sniper",
  jugg: "Juggernaut",
  pango: "Pangolier",
  mk: "Monkey King",
  tinker: "Tinker",
  ld: "Lone Druid",
  brood: "Broodmother",
  potm: "Mirana",
  underlord: "Underlord",
  ul: "Underlord",
  abaddon: "Abaddon",
  treant: "Treant Protector",
  tusk: "Tusk",
  ogre: "Ogre Magi",
  riki: "Riki",
  slardar: "Slardar",
  sven: "Sven",
  alch: "Alchemist",
  arc: "Arc Warden",
};
