import type { HeroTrait, Position } from "./traits.js";

/**
 * Curated, hand-maintained hero knowledge (mechanics, not statistics).
 * - positions: ordered, most common first
 * - provides: what the hero brings to a team
 * - weakTo: traits that counter the hero when an opponent provides them
 *
 * Keys are OpenDota `localized_name`s. Review after major patches; entries marked
 * lowConfidence are newer heroes and should be checked by someone who plays them.
 */
export interface HeroKnowledge {
  positions: Position[];
  provides: HeroTrait[];
  weakTo: HeroTrait[];
  lowConfidence?: boolean;
}

export const KNOWLEDGE_VERSION = "2026-09 (patch 7.41)";

const h = (positions: Position[], provides: HeroTrait[], weakTo: HeroTrait[], lowConfidence = false): HeroKnowledge => ({
  positions,
  provides,
  weakTo,
  ...(lowConfidence ? { lowConfidence } : {}),
});

export const HERO_KNOWLEDGE: Record<string, HeroKnowledge> = {
  Abaddon: h([5, 3, 1], ["save", "dispel", "sustain", "heal", "frontline"], ["break", "anti_heal", "silence"]),
  Alchemist: h([1, 2, 3], ["physical_damage", "frontline", "sustain", "disable", "tower_push"], ["anti_heal", "disable", "burst"]),
  "Ancient Apparition": h([5, 4], ["magical_damage", "anti_heal", "teamfight", "disable"], ["burst", "catch", "instant_disable"]),
  "Anti-Mage": h([1], ["mobility", "mana_burn", "physical_damage", "late_game", "tower_push"], ["instant_disable", "disable", "tower_push", "lane_harass"]),
  "Arc Warden": h([1, 2], ["physical_damage", "tower_push", "late_game", "magical_damage"], ["catch", "mobility", "instant_disable", "burst"]),
  Axe: h([3], ["initiation", "instant_disable", "frontline", "teamfight", "catch"], ["magical_damage", "disable", "lane_harass"]),
  Bane: h([5, 4], ["instant_disable", "disable", "catch", "save"], ["instant_disable", "burst", "catch"]),
  Batrider: h([3, 4, 2], ["initiation", "catch", "instant_disable", "mobility", "magical_damage"], ["silence", "instant_disable", "burst"]),
  Beastmaster: h([3, 2], ["initiation", "instant_disable", "summons", "tower_push", "catch"], ["wave_clear", "burst", "silence"]),
  Bloodseeker: h([1, 3, 2], ["silence", "anti_mobility", "catch", "physical_damage", "sustain"], ["instant_disable", "disable", "burst"]),
  "Bounty Hunter": h([4], ["invisibility", "catch", "disable", "physical_damage"], ["detection", "burst", "instant_disable"]),
  Brewmaster: h([3, 4], ["initiation", "frontline", "disable", "dispel", "summons", "teamfight"], ["instant_disable", "silence", "mana_burn"]),
  Bristleback: h([3, 1], ["frontline", "physical_damage", "teamfight"], ["break", "magical_damage", "armor_reduction"]),
  Broodmother: h([2, 1, 4], ["summons", "tower_push", "physical_damage", "mobility"], ["wave_clear", "instant_disable", "burst"]),
  "Centaur Warrunner": h([3], ["initiation", "instant_disable", "frontline", "save", "teamfight", "mobility"], ["physical_damage", "armor_reduction", "silence"]),
  "Chaos Knight": h([1, 3], ["instant_disable", "illusions", "physical_damage", "burst", "catch"], ["wave_clear", "disable", "magical_damage"]),
  Chen: h([5], ["heal", "summons", "tower_push", "save"], ["wave_clear", "burst", "catch"]),
  Clinkz: h([1, 2, 4], ["invisibility", "physical_damage", "burst", "tower_push"], ["detection", "instant_disable", "catch"]),
  Clockwerk: h([4, 3], ["initiation", "catch", "instant_disable", "anti_mobility", "frontline"], ["silence", "burst", "disable"]),
  "Crystal Maiden": h([5], ["disable", "teamfight", "magical_damage", "catch"], ["catch", "burst", "instant_disable"]),
  "Dark Seer": h([3], ["initiation", "teamfight", "illusions", "catch", "mobility"], ["silence", "burst", "instant_disable"]),
  "Dark Willow": h([4, 2], ["disable", "magical_damage", "burst", "catch"], ["instant_disable", "catch", "burst"]),
  Dawnbreaker: h([3, 4], ["frontline", "heal", "teamfight", "save", "sustain"], ["anti_heal", "magical_damage", "disable"]),
  Dazzle: h([5], ["save", "heal", "disable", "armor_reduction"], ["burst", "silence", "catch"]),
  "Death Prophet": h([2, 3], ["silence", "tower_push", "magical_damage", "teamfight", "sustain"], ["instant_disable", "catch", "burst"]),
  Disruptor: h([5, 4], ["silence", "catch", "anti_mobility", "teamfight", "magical_damage", "disable"], ["burst", "catch", "instant_disable"]),
  Doom: h([3], ["silence", "break", "catch", "frontline"], ["disable", "burst", "lane_harass"]),
  "Dragon Knight": h([1, 3, 2], ["frontline", "tower_push", "instant_disable", "physical_damage", "sustain"], ["magical_damage", "mobility", "break"]),
  "Drow Ranger": h([1], ["physical_damage", "silence", "tower_push"], ["catch", "mobility", "instant_disable", "burst"]),
  "Earth Spirit": h([4, 3], ["catch", "instant_disable", "silence", "mobility", "initiation"], ["silence", "instant_disable", "burst"]),
  Earthshaker: h([4, 3, 5], ["initiation", "instant_disable", "teamfight", "catch", "disable"], ["silence", "mana_burn", "burst"]),
  "Elder Titan": h([4, 5], ["armor_reduction", "teamfight", "instant_disable", "initiation"], ["burst", "catch", "silence"]),
  "Ember Spirit": h([2, 1], ["mobility", "burst", "magical_damage", "physical_damage", "disable"], ["silence", "instant_disable", "anti_mobility"]),
  Enchantress: h([4, 5, 1], ["summons", "heal", "disable", "sustain"], ["burst", "catch", "mobility"]),
  Enigma: h([3, 4], ["initiation", "teamfight", "instant_disable", "summons", "catch"], ["silence", "instant_disable", "burst"]),
  "Faceless Void": h([1], ["catch", "instant_disable", "physical_damage", "mobility", "late_game", "teamfight"], ["disable", "burst", "silence"]),
  Grimstroke: h([5, 4], ["silence", "catch", "disable", "magical_damage", "save"], ["burst", "catch", "instant_disable"]),
  Gyrocopter: h([1, 4], ["physical_damage", "magical_damage", "teamfight", "wave_clear", "disable"], ["catch", "burst", "instant_disable"]),
  Hoodwink: h([4], ["catch", "disable", "mobility", "physical_damage", "burst"], ["burst", "instant_disable", "catch"]),
  Huskar: h([2, 1], ["burst", "sustain", "magical_damage", "lane_harass", "spell_immunity"], ["break", "anti_heal", "physical_damage", "disable"]),
  Invoker: h([2, 4], ["magical_damage", "burst", "teamfight", "disable", "catch", "late_game"], ["catch", "silence", "burst", "instant_disable"]),
  Io: h([5], ["save", "heal", "mobility", "sustain"], ["burst", "catch", "instant_disable"]),
  Jakiro: h([5], ["wave_clear", "tower_push", "teamfight", "disable", "magical_damage"], ["catch", "burst", "mobility"]),
  Juggernaut: h([1], ["physical_damage", "spell_immunity", "sustain", "burst", "tower_push"], ["disable", "instant_disable", "catch"]),
  "Keeper of the Light": h([4, 5, 2], ["wave_clear", "magical_damage", "mobility", "disable"], ["catch", "burst", "mobility"]),
  Kez: h([2, 1], ["mobility", "burst", "physical_damage", "catch"], ["instant_disable", "silence", "burst"], true),
  Kunkka: h([3, 2], ["teamfight", "instant_disable", "save", "physical_damage", "frontline", "initiation"], ["mobility", "magical_damage", "silence"]),
  Largo: h([5, 4], ["teamfight", "sustain"], ["catch", "burst"], true),
  "Legion Commander": h([3, 1], ["catch", "instant_disable", "physical_damage", "dispel", "burst"], ["save", "disable", "mobility"]),
  Leshrac: h([2, 3], ["magical_damage", "tower_push", "wave_clear", "instant_disable", "teamfight"], ["silence", "mana_burn", "burst", "catch"]),
  Lich: h([5, 4], ["teamfight", "save", "disable", "magical_damage", "lane_harass"], ["catch", "burst", "mobility"]),
  Lifestealer: h([1, 3], ["physical_damage", "sustain", "spell_immunity", "frontline"], ["anti_heal", "disable", "mobility"]),
  Lina: h([2, 1, 4], ["magical_damage", "burst", "instant_disable", "physical_damage", "wave_clear"], ["catch", "burst", "mobility"]),
  Lion: h([5, 4], ["instant_disable", "burst", "catch", "magical_damage", "mana_burn"], ["catch", "burst", "instant_disable"]),
  "Lone Druid": h([1, 2], ["summons", "tower_push", "physical_damage", "frontline"], ["disable", "burst", "magical_damage"]),
  Luna: h([1], ["physical_damage", "magical_damage", "wave_clear", "tower_push", "teamfight"], ["catch", "burst", "instant_disable"]),
  Lycan: h([1, 3], ["summons", "tower_push", "physical_damage", "mobility"], ["wave_clear", "disable", "anti_mobility"]),
  Magnus: h([3, 2, 4], ["initiation", "teamfight", "instant_disable", "catch"], ["silence", "instant_disable", "burst"]),
  Marci: h([4, 1, 3], ["catch", "instant_disable", "burst", "physical_damage", "mobility"], ["disable", "burst", "mobility"]),
  Mars: h([3], ["initiation", "teamfight", "frontline", "catch", "instant_disable"], ["magical_damage", "mobility", "silence"]),
  Medusa: h([1, 2], ["physical_damage", "late_game", "teamfight", "wave_clear", "frontline"], ["mana_burn", "tower_push"]),
  Meepo: h([2, 1], ["burst", "catch", "physical_damage", "mobility", "tower_push"], ["wave_clear", "teamfight", "disable"]),
  Mirana: h([4, 2], ["catch", "instant_disable", "invisibility", "mobility", "magical_damage"], ["detection", "catch", "burst"]),
  "Monkey King": h([1, 2, 4], ["mobility", "physical_damage", "teamfight", "disable"], ["disable", "burst", "silence"]),
  Morphling: h([1], ["mobility", "burst", "physical_damage", "late_game"], ["instant_disable", "mana_burn", "silence", "burst"]),
  Muerta: h([1, 2], ["physical_damage", "magical_damage", "disable", "late_game"], ["catch", "mobility", "burst"]),
  "Naga Siren": h([1, 5], ["illusions", "tower_push", "physical_damage", "disable", "save", "catch"], ["wave_clear", "teamfight", "magical_damage"]),
  "Nature's Prophet": h([4, 1, 3], ["tower_push", "summons", "mobility", "catch", "physical_damage"], ["catch", "burst", "wave_clear"]),
  Necrophos: h([2, 3, 5], ["sustain", "heal", "magical_damage", "teamfight", "frontline"], ["anti_heal", "silence", "physical_damage"]),
  "Night Stalker": h([3, 1], ["catch", "silence", "physical_damage", "mobility", "frontline"], ["disable", "magical_damage", "mobility"]),
  "Nyx Assassin": h([4], ["burst", "instant_disable", "mana_burn", "invisibility", "catch"], ["detection", "burst", "catch"]),
  "Ogre Magi": h([5, 4], ["frontline", "instant_disable", "magical_damage", "physical_damage"], ["physical_damage", "armor_reduction"]),
  Omniknight: h([5, 4, 3], ["save", "heal", "dispel", "frontline", "sustain"], ["burst", "silence", "mana_burn"]),
  Oracle: h([5], ["save", "heal", "dispel", "disable"], ["burst", "catch", "instant_disable"]),
  "Outworld Devourer": h([2], ["magical_damage", "burst", "save", "disable"], ["mana_burn", "catch", "burst"]),
  Pangolier: h([3, 2, 4], ["initiation", "mobility", "disable", "teamfight", "physical_damage"], ["silence", "instant_disable", "anti_mobility"]),
  "Phantom Assassin": h([1], ["burst", "physical_damage", "mobility", "late_game"], ["disable", "instant_disable", "burst"]),
  "Phantom Lancer": h([1], ["illusions", "physical_damage", "mana_burn", "mobility", "late_game"], ["wave_clear", "teamfight"]),
  Phoenix: h([4, 5, 3], ["teamfight", "initiation", "magical_damage", "heal", "instant_disable"], ["anti_heal", "catch", "burst"]),
  "Primal Beast": h([3, 2], ["initiation", "frontline", "instant_disable", "teamfight", "catch", "magical_damage"], ["disable", "silence", "magical_damage"]),
  Puck: h([2], ["mobility", "wave_clear", "teamfight", "magical_damage", "silence", "initiation"], ["silence", "instant_disable", "mana_burn"]),
  Pudge: h([4, 3], ["catch", "instant_disable", "frontline", "magical_damage"], ["physical_damage", "mobility", "lane_harass"]),
  Pugna: h([2, 4], ["tower_push", "magical_damage", "burst", "save", "wave_clear"], ["catch", "burst", "mobility"]),
  "Queen of Pain": h([2], ["mobility", "magical_damage", "burst", "teamfight", "wave_clear"], ["silence", "instant_disable", "anti_mobility"]),
  Razor: h([1, 3, 2], ["physical_damage", "lane_harass", "frontline"], ["disable", "mobility", "magical_damage"]),
  Riki: h([4, 1], ["invisibility", "silence", "physical_damage", "burst"], ["detection", "disable", "instant_disable"]),
  "Ring Master": h([5, 4], ["disable", "catch", "save"], ["burst", "catch"], true),
  Rubick: h([4, 5], ["disable", "magical_damage", "save", "catch", "teamfight"], ["burst", "catch", "instant_disable"]),
  "Sand King": h([3, 4], ["initiation", "instant_disable", "teamfight", "wave_clear", "magical_damage"], ["silence", "instant_disable", "burst"]),
  "Shadow Demon": h([5, 4], ["save", "dispel", "illusions", "disable", "catch"], ["burst", "catch", "instant_disable"]),
  "Shadow Fiend": h([2, 1], ["physical_damage", "magical_damage", "burst", "wave_clear", "teamfight", "armor_reduction"], ["catch", "instant_disable", "silence", "burst"]),
  "Shadow Shaman": h([5, 4], ["instant_disable", "tower_push", "catch", "disable", "summons"], ["burst", "catch", "instant_disable"]),
  Silencer: h([5, 4, 2], ["silence", "teamfight", "anti_mobility", "lane_harass"], ["catch", "burst", "mobility"]),
  "Skywrath Mage": h([4, 5, 2], ["magical_damage", "burst", "silence", "lane_harass"], ["catch", "burst", "instant_disable"]),
  Slardar: h([3, 4], ["initiation", "instant_disable", "armor_reduction", "detection", "frontline", "physical_damage"], ["magical_damage", "disable", "mobility"]),
  Slark: h([1], ["mobility", "sustain", "dispel", "catch", "physical_damage"], ["instant_disable", "burst", "disable"]),
  Snapfire: h([4, 5], ["instant_disable", "magical_damage", "teamfight", "mobility"], ["catch", "burst", "mobility"]),
  Sniper: h([2, 1, 4], ["physical_damage", "lane_harass", "late_game", "tower_push"], ["catch", "mobility", "burst"]),
  Spectre: h([1], ["late_game", "mobility", "physical_damage", "frontline"], ["tower_push", "break", "lane_harass"]),
  "Spirit Breaker": h([4, 3], ["initiation", "catch", "mobility", "instant_disable"], ["disable", "instant_disable", "burst"]),
  "Storm Spirit": h([2], ["mobility", "magical_damage", "burst", "catch"], ["silence", "anti_mobility", "mana_burn", "instant_disable"]),
  Sven: h([1], ["physical_damage", "instant_disable", "teamfight", "burst"], ["disable", "mobility", "burst"]),
  Techies: h([4, 5], ["magical_damage", "burst", "silence", "disable"], ["detection", "catch", "burst"]),
  "Templar Assassin": h([2, 1], ["burst", "physical_damage", "armor_reduction", "invisibility", "lane_harass"], ["detection", "instant_disable", "magical_damage"]),
  Terrorblade: h([1], ["illusions", "physical_damage", "tower_push", "late_game"], ["wave_clear", "burst", "catch"]),
  Tidehunter: h([3, 4], ["initiation", "teamfight", "instant_disable", "frontline", "dispel"], ["break", "mana_burn", "silence"]),
  Timbersaw: h([3, 2], ["mobility", "magical_damage", "frontline", "wave_clear"], ["silence", "instant_disable", "mana_burn"]),
  Tinker: h([2], ["magical_damage", "burst", "wave_clear", "tower_push", "mobility"], ["catch", "instant_disable", "burst", "silence"]),
  Tiny: h([2, 4, 1], ["burst", "instant_disable", "catch", "physical_damage", "initiation", "tower_push"], ["disable", "magical_damage", "burst"]),
  "Treant Protector": h([5, 4], ["heal", "initiation", "catch", "disable", "teamfight"], ["burst", "catch", "silence"]),
  "Troll Warlord": h([1], ["physical_damage", "tower_push", "sustain", "late_game"], ["disable", "mobility", "instant_disable"]),
  Tusk: h([4, 3], ["initiation", "catch", "instant_disable", "save", "disable"], ["burst", "silence", "instant_disable"]),
  Underlord: h([3], ["frontline", "teamfight", "wave_clear", "disable", "mobility"], ["physical_damage", "armor_reduction", "mobility"]),
  Undying: h([5, 4], ["frontline", "heal", "summons", "teamfight"], ["wave_clear", "anti_heal", "burst"]),
  Ursa: h([1, 3], ["physical_damage", "burst", "frontline"], ["disable", "mobility", "lane_harass"]),
  "Vengeful Spirit": h([5, 4], ["instant_disable", "save", "armor_reduction", "catch"], ["burst", "catch"]),
  Venomancer: h([5, 3, 4], ["lane_harass", "magical_damage", "teamfight", "disable", "summons"], ["catch", "burst", "dispel"]),
  Viper: h([3, 2, 1], ["lane_harass", "break", "magical_damage", "disable", "frontline"], ["disable", "physical_damage", "mobility"]),
  Visage: h([2, 5], ["summons", "instant_disable", "magical_damage", "burst", "tower_push"], ["wave_clear", "burst", "catch"]),
  "Void Spirit": h([2, 3], ["mobility", "burst", "magical_damage", "catch", "disable"], ["silence", "instant_disable", "anti_mobility"]),
  Warlock: h([5, 4], ["teamfight", "instant_disable", "heal", "summons", "disable"], ["catch", "burst", "silence"]),
  Weaver: h([1, 4], ["invisibility", "mobility", "physical_damage"], ["detection", "instant_disable", "burst"]),
  Windranger: h([2, 4, 1], ["physical_damage", "instant_disable", "catch", "mobility", "magical_damage"], ["instant_disable", "burst", "catch"]),
  "Winter Wyvern": h([5, 4], ["save", "teamfight", "disable", "magical_damage", "heal"], ["catch", "burst", "instant_disable"]),
  "Witch Doctor": h([5, 4], ["heal", "instant_disable", "magical_damage", "teamfight"], ["catch", "burst", "instant_disable"]),
  "Wraith King": h([1, 3], ["physical_damage", "instant_disable", "frontline", "sustain", "summons"], ["mana_burn", "anti_heal", "disable"]),
  Zeus: h([2, 4, 5], ["magical_damage", "burst", "detection", "teamfight", "lane_harass"], ["catch", "burst", "mobility"]),
};

export function getKnowledge(localizedName: string): HeroKnowledge | undefined {
  return HERO_KNOWLEDGE[localizedName];
}
